---
title: "Ishita's Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: [ "twitter", "facebook", "menu"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(DT)
library(rpivotTable)
library(ggplot2)
library(plotly)
library(dplyr)
library(openintro)
library(highcharter)
library(ggvis)
```


```{r}
data <- read.csv("vehicle.csv")
```

```{r}
mycolors <- c("red", "#FFC125", "pink", "yellow")
```

Data Visualization
=====================================

Row
-------------------------------------

### Analysis

```{r}
valueBox(paste("Car Failure"),
         color = "warning",)
```

### Car Failures in US

```{r}
valueBox(length(data$State),
         icon = "fa-car")
```

### **Labor Cost**

```{r}
gauge(round(mean(data$lc),
            digits = 2),
            min = 0,
            max = 350,
            gaugeSectors(success = c(0, 150),
                         warning = c(150, 240),
                         danger = c(240, 350),
                         colors = c("green", "yellow", "red")))
```
### Texas

```{r}
valueBox(sum(data$State == "TX"),
         icon = 'ion-ios-location')
```


### California

```{r}
valueBox(sum(data$State == "CA"),
         icon = 'ion-ios-location')
```

### Georgia

```{r}
valueBox(sum(data$State == "GA"),
         icon = 'ion-ios-location',color="primary")
```


### Arizona

```{r}
valueBox(sum(data$State == "AZ"),
         icon = 'ion-ios-location')
```

Row
-------------------------------

### Top States

```{r}
p1 <- data %>%
         group_by(State) %>%
         summarise(count = n()) %>%
         filter(count>50) %>%
         plot_ly(labels = ~State,
                 values = ~count,
                 marker = list(colors = mycolors)) %>%
         add_pie(hole = 0.2) %>%
         layout(xaxis = list(zeroline = F,
                             showline = F,
                             showticklabels = F,
                             showgrid = F),
                yaxis = list(zeroline = F,
                             showline = F,
                             showticklabels=F,
                             showgrid=F))
p1
```


### FM Vs Mileage

```{r}
p2 <- plot_ly(data,
              x = ~fm,
              y = ~Mileage,color = "#00BFC4",
              text = paste("FM:", data$fm,
                           "Mileage:",
                           data$Mileage),
              type = "bar") %>%
         layout(xaxis = list(title="FM"),
                yaxis = list(title = "Failure Mileage"))
p2
```

### Failures By State

```{r}
p3 <- data %>%
         group_by(State) %>%
         summarise(count = n()) %>%
         plot_ly(x = ~State,
                 y = ~count,
                 color = rainbow(51),
                 type = 'bar') %>%
layout(xaxis = list(title = "Failures By State"),
yaxis = list(title = 'Count'))
p3
```





Row
------------------------------------

### Box Plot of Top State vs labor cost

```{r fig.height=6, fig.width=6}
data %>%
         group_by(State) %>%
         ggvis(~State, ~lc, fill = ~State) %>%
         layer_boxplots()
```

### Scatter Plot of Month Vs Mileage

```{r}
p4 <- plot_ly(data, x=~fm) %>%
         add_markers(y = ~Mileage,
                     text = ~paste("Mileage: ", Mileage),
                     showlegend = F) %>%
         
         layout(xaxis = list(title = "Month"),
                yaxis = list(title = "Mileage"))
p4
```


Map
========================================

### Map

```{r}
car <- data %>%
         group_by(State) %>%
         summarize(total = n())
car$State <- abbr2state(car$State)

highchart() %>%
         hc_title(text = "Car Failures in US") %>%
         hc_subtitle(text = "Source: vehicle.csv") %>%
         hc_add_series_map(usgeojson, car,
                           name = "State",
                           value = "total",
                           joinBy = c("woename", "State")) %>%
         hc_mapNavigation(enabled = T)
```



Pivot Table
=========================================

```{r}
rpivotTable(data,
            aggregatorName = "Count",
            cols= "fm",
            rows = "State",
            rendererName = "Area Chart")
```

Summary {data-orientation=columns} 
===========================================

Column 
-----------------------------------

### Max Failure Month

```{r}
valueBox(max(data$fm),
         icon = "ion-ios-gear" )
```

### Average Labor hours
```{r}
valueBox(round(mean(data$lh),
               digits = 2),
         icon = "ion-android-contacts")
```
### Average Labor cost
```{r}
valueBox(round(mean(data$lc),
               digits = 2),
         icon = "ion-cash")
```

### Average Mileage at Failure

```{r}
valueBox(round(mean(data$Mileage), digits = 2),
         icon = "ion-ios-speedometer")
```

Column
---------------------------

Report

* This is a report on `r length(data$fm)` car failures.

* The average labor cost was `r mean(data$lc)`.

* The average material cost was `r mean(data$mc)`.

This report was generated on `r format(Sys.Date(), format = "%B %d, %Y")`.







